### ISSUE TITLE
Can't install SiEPIC tools/PDK

### ISSUE THREAD

**Issue by stratomaster31** [SiEPIC/SiEPIC-Tools#126]
Hi,

The pacakage manager is unable to get SiEPIC installed, mirror inks to the repository are broken...

![image](https://user-images.githubusercontent.com/22171434/88974759-6c8a3100-d2b9-11ea-9628-2310b8430b85.png)

Tank you very much for your time and your fantastic work!

**Comment by lukasc-ubc** [comment]
Have you been able to get it to work?
