### ISSUE TITLE
Script error with converting paths to waveguides

### ISSUE THREAD

**Issue by MrGodlikePro** [SiEPIC/SiEPIC-Tools#131]
I come up with the "Waveguid in SiEPIC General library is not available." error (see image) when converting paths to waveguides in KLayout, specifically with the AMF technology selected (When EBeam is selected this works fine). I have tried to update the packages.

I tried on another computer with the following package versions before updating:

- Python_packages_for_KLayout 1.1 (1.2 is the current version)
- siepic_tools 0.3.67 (0.3.69 is the current version)

And it worked fine. So i guess it is a problem with the updated versions of the packages. Is there a way to revert the version of the packages?

![image](https://user-images.githubusercontent.com/38740430/92736148-024cbd80-f348-11ea-8b44-08e2d307c64c.png)

**Comment by mustafacc** [comment]
Thanks @MrGodlikePro 
We've had an update on path-to-waveguide functionality that would require a "waveguide" pcell to exist in the library - seems like AMF didn't that waveguide pcell. I'll add that waveguide pcell to the AMF PDK now.

Closing this issue now here now and reopening on AMF PDK
