### ISSUE TITLE
The function "Compute area" makes me confused

### ISSUE THREAD

**Issue by Zwlzzm** [SiEPIC/SiEPIC-Tools#141]
Hi,

I am using klayout 0.26.9. The  SiEPIC version is 0.3.72 Py2.
It create a wire waveguide using path and "path to wireguide" function.
It is  4*10um. However, the function "Compute area" shows the area is  120.35um2.
![image](https://user-images.githubusercontent.com/22097935/110404531-facd5d80-80b9-11eb-9b8c-3d386e0c3408.png)
And for the same structure, open klayout again, the calculated area value is not the same
![image](https://user-images.githubusercontent.com/22097935/110405291-50563a00-80bb-11eb-9a35-df83e470559b.png)

This is also the case for component Ebeam waveguide_sbend. It shows the area of a waveguide_bend with a radius of 10um and a width of 0.5um is also 71.424 um2.

![image](https://user-images.githubusercontent.com/22097935/110405613-cf4b7280-80bb-11eb-91d2-2cb5faa23eb0.png)

**Comment by lukasc-ubc** [comment]
First, this function calculates the area covered by the Waveguide layer over the entire layout.  It does not consider the selected object.

Could you attach a layout that isn’t being calculated correctly?

thanks

**Comment by Zwlzzm** [comment]
Dear Professor Lukas,

Thank you for your respond.  I think I misunderstood the meaning of this function.

For Ebeam waveguide_sbend with radius of 10um, width of 0.5um. The area calculated is 7.8561um2.
But using the area formula for ring structure (pi*(10.25*10.25-9.75*9.75)/4), this value is 7.85398um2.. 
There is a slight difference. Is this because that Ebeam waveguide_sbend has a certain number of points (It is not a complete ring)?

[test.zip](https://github.com/SiEPIC/SiEPIC-Tools/files/6106060/test.zip)


Beside, about how to launch lumerical from klayout siepic on Centos, Lumerical support has not have a good resolution, and they suggest me ask you for help. Could you give me some suggestions?
https://github.com/SiEPIC/SiEPIC_EBeam_PDK/issues/234

Best regards!

**Comment by lukasc-ubc** [comment]
I believe a new nm rounding error can be expected.
The purpose of this function is to estimate the ebeam writing time.

**Comment by Zwlzzm** [comment]
Thank you for your respond and explanation. I got it.
