### ISSUE TITLE
Siepic Tools not able to be found in salt

### ISSUE THREAD

**Issue by alexsludds** [SiEPIC/SiEPIC-Tools#158]
Hi all,
I am trying to reinstall siepic tools in salt on klayout 0.27.3
However, it does not appear on the list of available packages.
If I try to install siepic_ebeam_pdk it says that it can't find siepic tools in the package index.

**Comment by alexsludds** [comment]
Sorry. I'm going to be "that guy" and bump this just because I need Siepic tools working soon for a tapeout I am doing.

**Comment by alexsludds** [comment]
Hi folks, is there just not people maintaining this software anymore? It's been incredibly helpful for my graduate research and saved me countless days of time. I would hate to see it become "abandonware"

**Comment by alexsludds** [comment]
Still waiting for this to be addressed.... my tapeout is in a week. Can someone please respond?

**Comment by mustafacc** [comment]
Hi Alex, 

sorry for the delay on this. There are issues with the KLayout Package Manager (KLayout side) and the only way to install the packages is to manually fetch the repository:

1- Download the SiEPIC Tools repository (and any other SiEPIC PDKs you want to use for the tapeout, if any)
2- Copy the content "klayout_dot_config" file in the repository
3- Go to your KLayout config file (in windows it should be in C:/users/you/klayout
4- Create a folder called "salt", if it exists already, proceed to the next step
5- Create a folder inside salt folder called "siepic_tools"
6- Paste the copied content from the repository to this newly created folder.
7- Repeat this process for any other SiEPIC package/PDK

Note that you're manually copying content from the repository to the KLayout folder, therefore, you need to keep updating the package manually. I highly recommend creating a symbolic link between the repo and the klayout-salt-siepic_tools folder such that you get the latest content as the repo updates.


The SiEPIC Tools is an open source project maintained by developers who volunteer their free time to keep it up and running, it is definitely not abandoned :)

Good luck on your tape-out!

**Comment by dichium** [comment]
Dear Mr. @mustafacc 

Please help me in solving the problem of not being able to connect (snap component 'shift+o' between the grating coupler and y-branch) in the component library in EBeam v0.3.37. I want to learn about MZI and want to simulate on KLayout for my graduate research.  I use Windows 10 64-bit and have managed packages as I have seen on this forum. is there a step I missed? so my KLayout can't connect between respective device libraries. thank you please help.
![image](https://user-images.githubusercontent.com/76896572/144775486-9a6cdc9b-dd27-4400-ae87-6a78046da853.png)

**Comment by lukasc-ubc** [comment]
Could you please use KLayout 0.27.5?  We stopped supporting 0.26.
