### ISSUE TITLE
waveguide length difference measurement function

### ISSUE THREAD

**Issue by lukasc-ubc** [SiEPIC/SiEPIC-Tools#168]
@jaspreetj 
The waveguide length difference measurement function is not working, in the EBeam PDK.

<img width="621" alt="image" src="https://user-images.githubusercontent.com/15843200/160670083-9f13c285-5193-4e07-8df2-fb19a2e06745.png">

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/15843200/160670026-cc002053-72b6-463b-91ed-b63443420b35.png">
<img width="912" alt="image" src="https://user-images.githubusercontent.com/15843200/160670045-ea8ee1ee-1046-4801-bb5d-137b5bd6202d.png">

**Comment by jaspreetj** [comment]
I just deployed a fix. Let me know if you experience any issues.
