### ISSUE TITLE
GitHub shuts down SVN bridge: KLayout package will need mirror at SourceForge

### ISSUE THREAD

**Issue by klayoutmatthias** [SiEPIC/SiEPIC-Tools#193]
Starting Jan. 8 2024, GitHub SVN access will be disabled. This means, the convenient way of deploying KLayout packages will stop working. A short-term solution is to mirror the KLayout Package part to a Subversion project on SourceForge.

This topic is tracked here: https://github.com/KLayout/klayout/issues/1514

**Comment by lukasc-ubc** [comment]
Thank you for implementing the new GitHub protocol.
