### ISSUE TITLE
Unable to use "Waveguide" functions in KLayout

### ISSUE THREAD

**Issue by ytluyt** [SiEPIC/SiEPIC-Tools#208]
Hi,
I want to round the waveguides of layout in KLayout, but it always shows the error as below:
![image](https://github.com/SiEPIC/SiEPIC-Tools/assets/118702662/413d1e71-c253-4de7-953f-d6193fb519ea)

![image](https://github.com/SiEPIC/SiEPIC-Tools/assets/118702662/adee6f99-ff1b-4c3c-a92c-f2c7e83dc392)

Could you please help me check?
Thank you!

**Comment by lukasc-ubc** [comment]
I believe this has been resolved.
