### ISSUE TITLE
Unable to use the example layout

### ISSUE THREAD

**Issue by weimaoliang** [SiEPIC/SiEPIC-Tools#233]
Could any one help me with the problem when trying the example layout, it doesn't work as expected.
![image](https://github.com/user-attachments/assets/eca55889-d97b-4cd9-bf91-891f0daff1a0)
![image](https://github.com/user-attachments/assets/ce48b0c4-a478-41e8-970a-b2d423fff03c)

**Comment by lukasc-ubc** [comment]
I just fixed the example and updated the package.

the error was with:

        cell_ebeam_y_dream = ly.create_cell('ebeam_dream_splitter_1x2_te1550_BB', 'EBeam-Dream',{})

the fix is:

        cell_ebeam_y_dream = ly.create_cell('ebeam_dream_splitter_1x2_te1550_BB', 'EBeam-Dream')
